### ISSUE TITLE
Questions about `geoip` and `geosite` files.

### ISSUE THREAD

**Issue by hawshemi** [Chocolate4U/Iran-v2ray-rules#9]
1. Are these :

```
geoip:arvancloud
geoip:derakcloud
geoip:iranserver
geoip:parspack
```
included in `geoip:ir` ?

2. for malware & phishing blocking, should I use both `geoip:malware/phishing` and `geosite:malware/phishing`? or one of them is enough?

3. what are the differences between `"geosite:category-ir"` _(from loyalsoldier)_ and your `geosite:ir`?

4. what are the differences between `"geosite:category-ads-all"` _(from loyalsoldier)_ and your `geosite:category-ads-all`?

**Comment by Chocolate4U** [comment]
1. No, due to the limitation of Maxmind's `.mmdb` format, there can be only 1 copy of each IP address.  Therefore we can't include them both in `geoip:ir` and their respective category. This also true for sing-box `.db` files which are based on `.mmdb` files. but for v2ray `.dat` files, they don't have this limitation and because some of these CDN's IP addresses are already included in Maxmind and IP2location databases, they are also present in `geoip.dat:ir` but not as complete as CDN's seperate categories.

2. Yes you have to use both of them. Some malwares are served via IP address only, without any domain name. 

3. `geosite:category-ir` has limited and incomplete Iranian domains, while `geosite:ir` contains domains from [iran-hosted-domains](https://github.com/bootmortis/iran-hosted-domains) which includes all of `geosite:category-ir` + many more Iranian domains from multiple sources.

4. My `geosite:category-ads-all` is way more comprehensive than loyalsoldier's `geosite:category-ads-all`. you can see the full list of blocklists in Sources section. It also includes Persian Ads from [PersianBlocker](https://github.com/MasterKia/PersianBlocker) which the latter doesn't.

**Comment by hawshemi** [comment]
Thanks.
